import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { BackgroundLines } from "@/components/ui/background-lines";
import { ModeToggle } from "@/components/mode-toggle";
import SplashCursor from "@/blocks/Animations/SplashCursor/SplashCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Snap Spot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <BackgroundLines className="flex flex-col justify-center items-center w-full">
            {children}
            <div className="top-8 right-8 z-50 absolute">
              <ModeToggle />
            </div>
            <div className="top-0 right-0 bottom-0 left-0 absolute">
              <SplashCursor />
            </div>
          </BackgroundLines>
        </ThemeProvider>
      </body>
    </html>
  );
}
