import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { ModeToggle } from "@/components/mode-toggle";
import { PointerWrapper } from "@/components/magicui/pointer";
import Link from "next/link";
import { ShinyButton } from "@/components/magicui/shiny-button";
import { Github } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Snap Spot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <div className="top-8 right-8 z-50 absolute">
            <ModeToggle />
          </div>
          <div className="top-8 left-8 z-50 absolute">
            <Link href={"https://github.com/ekaputra04/snap-spot.git"}>
              <ShinyButton>View on Github</ShinyButton>
            </Link>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
